version: '3.8'

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: controller
    volumes:
      - .:/home/ansible
    tty: true

  web1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: web1
    hostname: web1

  web2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: web2
    hostname: web2

  db1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: db1
    hostname: db1

  db2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: db2
    hostname: db2
